# set -g mouse
set -g @plugin 'tmux-plugins/tpm'

# themes
# set -g @plugin "nordtheme/tmux"
# set -g @plugin 'odedlaz/tmux-onedark-theme'
# set -g @plugin 'catppuccin/tmux'
# set -g @plugin 'christoomey/vim-tmux-navigator'
# set -g @plugin 'tmux-plugins/tmux-continuum'
# set -g @plugin 'egel/tmux-gruvbox'
# set -g @tmux-gruvbox 'dark' # or 'light'
set -g @plugin 'catppuccin/tmux#v2.1.3' # See https://github.com/catppuccin/tmux/tags for additional tags
set -g @catppuccin_flavor 'mocha' # latte, frappe, macchiato or mocha

set -g @plugin "MunifTanjim/tmux-mode-indicator"

set -g @plugin 'wfxr/tmux-fzf-url'
set -g @fzf-url-bind 'r'

# replace f key with fingers
set -g @plugin 'Morantron/tmux-fingers'
unbind f
set -g @fingers-key f

# TODO: figure out copy mode
set -g @plugin 'tmux-plugins/tmux-yank'
setw -g mode-keys vi
set -s set-clipboard on
bind -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel

set -g @plugin 'tmux-plugins/tmux-sensible'
unbind-key C-b
set-option -g prefix C-f
bind-key C-f send-prefix

set -g default-terminal "tmux-256color"
set-option -sa terminal-overrides ',*:Tc'
# set-option -g default-shell /bin/zsh

# TODO remove, meta-R is reload
bind M source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded"

# Set new panes to open in current directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Extra keybinds, cant macro some on ergodox
bind-key r command-prompt -I "#S" "rename-session '%%'"
bind i split-window -h -c "#{pane_current_path}"
bind u split-window -v -c "#{pane_current_path}"
bind e new-session
# bind g copy-mode

bind -n M-H resize-pane -L 2
bind -n M-L resize-pane -R 2
bind -n M-K resize-pane -U 2
bind -n M-J resize-pane -D 2

bind-key "k" run-shell "sesh connect \"$(
  sesh list --icons | fzf-tmux -p 80%,70% \
    --no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
    --header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
    --bind 'tab:down,btab:up' \
    --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list --icons)' \
    --bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t --icons)' \
    --bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c --icons)' \
    --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z --icons)' \
    --bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
    --bind 'ctrl-d:execute(tmux kill-session -t {2..})+change-prompt(⚡  )+reload(sesh list --icons)' \
    --preview-window 'right:55%' \
    --preview 'sesh preview {}'
)\""

# fix esc in vim
set -s escape-time 0

# auto restore tmux sessions
set -g @continuum-restore 'on'

# latte, frappe, macchiato, mocha
# set -g @catppuccin_flavour 'macchiato'

# start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

set -g renumber-windows on
setw -g mode-keys vi

bind-key x kill-pane # skip "kill-pane 1? (y/n)" prompt
set -g detach-on-destroy off  # don't exit from tmux when closing a session
set -g @t-bind "s"

# status bar
set -g status-justify left
set -g status-position top

# last session keybind
bind-key -T prefix l switch-client -l
bind-key -T prefix L last-window

# # tmux-plugins/tmux-prefix-highlight support
# set -g @prefix_highlight_output_prefix "#[fg=#e0af68]#[bg=#1f2335]#[fg=#1f2335]#[bg=#e0af68]"
# set -g @prefix_highlight_output_suffix ""

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
