# uncomment to profile
#zmodload zsh/zprof

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
export ZSH=$HOME/.oh-my-zsh
bindkey -v

setopt AUTO_PARAM_SLASH       # adds slash at end of tabbed dirs
setopt CHECK_JOBS             # check bg jobs on exit
setopt EXTENDED_GLOB          # globs #, ~ and ^
setopt EXTENDED_HISTORY       # saves timestamps on history
setopt GLOB_DOTS              # find dotfiles easier
setopt HASH_CMDS              # save cmd location to skip PATH lookup
setopt HIST_EXPIRE_DUPS_FIRST # expire duped history first
setopt HIST_NO_STORE          # dont save history cmd in history
setopt INC_APPEND_HISTORY     # append history as command are entered
setopt LIST_ROWS_FIRST        # completion options left-to-right, top-to-bottom
setopt LIST_TYPES             # show file types in list
setopt MARK_DIRS              # adds slash to end of completed dirs
setopt SHARE_HISTORY          # share history between open shells
setopt MAGIC_EQUAL_SUBST      # make filename completion after equal sign work
unsetopt AUTOCD               # dont allow when just typing folder name
unsetopt BEEP		      # turn off beep

DOTFILES="$HOME/.dotfiles"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
zstyle ':omz:update' frequency 13

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment if git is slow
# DISABLE_UNTRACKED_FILES_DIRTY="true"

HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.histfile
HIST_STAMPS="yyyy-mm-dd"

DISABLE_AUTO_TITLE="true"

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin":$PATH
eval "$(pyenv init --path)"

export SPACESHIP_CONFIG="$HOME/.dotfiles/zsh/spaceship.zsh"

source $DOTFILES/zsh/zsh_aliases
# source $DOTFILES/zsh/zsh_theme

# antigen
source $DOTFILES/zsh/antigen.zsh

antigen bundle autopep8
antigen bundle colorize
antigen bundle command-not-found
antigen bundle common-aliases
antigen bundle dirhistory
antigen bundle docker
antigen bundle git
antigen bundle xylous/gitstatus
antigen bundle history
antigen bundle pip
#antigen bundle pipenv
antigen bundle pyenv
antigen bundle python
antigen bundle terraform
antigen bundle tmux
antigen bundle vault
antigen bundle starship
antigen bundle agkozak/zsh-z
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-syntax-highlighting
# antigen bundle vi-mode
# antigen bundle jeffreytse/zsh-vi-mode
# antigen bundle spaceship-prompt/spaceship-vi-mode@main
antigen bundle sawadashota/go-task-completions

# antigen theme spaceship-prompt/spaceship-prompt

antigen use oh-my-zsh

antigen apply

ZSH_TMUX_AUTOSTART=false   # auto start tmux
ZSH_TMUX_UNICODE=true      # enable unicode
ZSH_TMUX_AUTOCONNECT=true  # dont autoconnect

# VI_MODE_RESET_PROMPT_ON_MODE_CHANGE=true
# VI_MODE_SET_CURSOR=true
# VI_MODE_CURSOR_NORMAL=2
# VI_MODE_CURSOR_VISUAL=3
# VI_MODE_CURSOR_INSERT=6
bindkey '\C-e' edit-command-line

# completion
zstyle ':completion:*' list-colors "${(@s.:.)LS_COLORS}"
zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

autoload -U compinit && compinit

# extra completion
if (( $+commands[kubectl] )); then
  source <(kubectl completion zsh)
fi
if (( $+commands[glab] )); then
  source <(glab completion -s zsh); compdef _glab glab
fi

# enable fzf keybinds
source /usr/share/doc/fzf/examples/key-bindings.zsh

# ssh host completion
zstyle -e ':completion:*:(ssh|scp|sftp|rsh|rsync):hosts' hosts 'reply=(${=${${(f)"$(cat {/etc/ssh_,~/.ssh/known_}hosts(|2)(N) /dev/null)"}%%[# ]*}//,/ })'

# uncomment to profile
#zprof

[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"

export PATH="$HOME/.local/bin":$PATH
export PATH="$HOME/go/bin":$PATH

source $HOME/.secrets

# settings that should be defaul
export ANSIBLE_NOCOWS=1
export PIPENV_VENV_IN_PROJECT=1

# eval "$(starship init zsh)"
eval "$(zoxide init zsh)"

# fzf theme
# made using https://minsw.github.io/fzf-color-picker/
export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS'
  --color=fg:#a89984,bg:#282828,hl:#83a598
  --color=fg+:#fbf1c7,bg+:#3c3836,hl+:#458588
  --color=info:#665c54,prompt:#fe8019,pointer:#b8bb26
  --color=marker:#d3869b,spinner:#d65d03,header:#98971a'
